apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    app: result
---
apiVersion: v1
kind: Service
metadata:
  name: result-external
spec:
  type: LoadBalancer
  ports:
  - name: "result-service"
    port: 8001
    targetPort: 80
  selector:
    app: result
