apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote
---
apiVersion: v1
kind: Service
metadata:
  name: vote-external
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: 8000
    targetPort: 80
  selector:
    app: vote
